{% set name = "pycountry" %}
{% set version = "26.2.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5b6027d453fcd6060112b951dd010f01f168b51b4bf8a1f1fc8c95c8d94a0801

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.0.0
  run:
    - python
    - importlib-resources >5.12.0  # [py<39]

test:
  imports:
    - pycountry
  requires:
    - pip
    - pytest >7.1.3
  commands:
    - pip check
    - python -c "import pycountry; print(len(pycountry.countries))"
    - python -c "import pycountry; print(len(pycountry.languages))"
    - python -c "import pycountry; print(len(pycountry.currencies))"
    - pytest --pyargs pycountry.tests.test_general

about:
  home: https://github.com/flyingcircusio/pycountry
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: ISO country, subdivision, language, currency and script definitions and their translations
  doc_url: https://github.com/flyingcircusio/pycountry
  dev_url: https://github.com/flyingcircusio/pycountry

extra:
  recipe-maintainers:
    - anaconda
